var randomlinks=new Array(100)

         randomlinks[0]="/Pages/games/learntofly/"
         randomlinks[1]="/Pages/games/mario/"
         randomlinks[2]="/Pages/games/interactivebuddy/"
         randomlinks[3]="/Pages/games/helicopter/"
         randomlinks[4]="/Pages/games/push-the-square/"
         randomlinks[5]="/Pages/games/crossyroad/"
         randomlinks[6]="/Pages/games/creativekillchamber/"
         randomlinks[7]="/Pages/games/ezr2/"
         randomlinks[8]="/Pages/games/doodle-jump/"
         randomlinks[9]="/Pages/games/motox3m-spooky/"
         randomlinks[10]="/Pages/games/pandemic2/"
         randomlinks[11]="/Pages/games/justfall/"
         randomlinks[12]="/Pages/games/fnaf2/"
         randomlinks[13]="/Pages/games/fnaf/"
         randomlinks[14]="/Pages/games/fnaf4/"
         randomlinks[15]="/Pages/games/breakout/"
         randomlinks[16]="/Pages/games/goodnight/"
         randomlinks[17]="/Pages/games/worlds-hardest-game/"
         randomlinks[18]="/Pages/games/sans/"
         randomlinks[19]="/Pages/games/boxing-physics/index.html/"
         randomlinks[20]="/Pages/games/game-inside/"
         randomlinks[21]="/Pages/games/geodash/"
         randomlinks[22]="/Pages/games/hba/"
         randomlinks[23]="/Pages/games/solitaire/"
         randomlinks[24]="/Pages/games/wpnfire/"
         randomlinks[25]="/Pages/games/rooftop-snipers/"
         randomlinks[26]="/Pages/games/1/"
         randomlinks[27]="/Pages/games/basketball-stars/"
         randomlinks[28]="/Pages/games/ngon/"
         randomlinks[29]="/Pages/games/tetris/"
         randomlinks[30]="/Pages/games/chromedino/"
         randomlinks[31]="/Pages/games/connect3/"
         randomlinks[32]="/Pages/games/escapingtheprison/"
         randomlinks[33]="/Pages/games/xx142-b2exe/"
         randomlinks[34]="/Pages/games/pacman/"
         randomlinks[35]="/Pages/games/Subway-Surfers/"
         randomlinks[36]="/Pages/games/2048/"
         randomlinks[37]="/Pages/games/asciispace/"
         randomlinks[38]="/Pages/games/asteroids/"
         randomlinks[39]="/Pages/games/evilglitch/"
         randomlinks[40]="/Pages/games/ninjavsevilcorp/"
         randomlinks[41]="/Pages/games/racer/"
         randomlinks[42]="/Pages/games/minesweeper/"
         randomlinks[43]="/Pages/games/radiusraid/"
         randomlinks[44]="/Pages/games/shuttledeck/"
         randomlinks[45]="/Pages/games/sleepingbeauty/"
         randomlinks[46]="/Pages/games/retrobowl/"
         randomlinks[47]="/Pages/games/slope-2/"
         randomlinks[48]="/Pages/games/slope/"
         randomlinks[49]="/Pages/games/time-shooter-2/"
         randomlinks[50]="/Pages/games/tube-jumpers/"
         randomlinks[51]="/Pages/games/cookie-clicker/"
         randomlinks[52]="/Pages/games/incremancer/"
         randomlinks[53]="/Pages/games/bitlife/"
         randomlinks[54]="/Pages/games/tunnel-rush/"
         randomlinks[55]="/Pages/games/impossiblequiz/"
         randomlinks[56]="/Pages/games/just-one-boss/"
         randomlinks[57]="/Pages/games/paperio2/"
         randomlinks[58]="/Pages/games/ducklife1/"
         randomlinks[59]="/Pages/games/ducklife2/"
         randomlinks[60]="/Pages/games/ducklife3/"
         randomlinks[61]="/Pages/games/adarkroom/"
         randomlinks[62]="/Pages/games/agario-minigame/"
         randomlinks[63]="/Pages/games/basket-random/"
         randomlinks[64]="/Pages/games/tank-trouble-2/"
         randomlinks[65]="/Pages/games/papasb/"
         randomlinks[66]="/Pages/games/backrooms/"
         randomlinks[67]="/Pages/games/baldi/"
         randomlinks[68]="/Pages/games/soundboard/"
         randomlinks[69]="/Pages/games/Flappy-2048/"
         randomlinks[70]="/Pages/games/csgo-clicker/"
         randomlinks[71]="/Pages/games/edgenotfound/"
         randomlinks[72]="/Pages/games/ultimate-flash-sonic"
         randomlinks[73]="/Pages/games/ageofwar"
         randomlinks[74]="https://scratch.mit.edu/projects/292728003/fullscreen/"
         randomlinks[75]="/Pages/games/you-are-bezos"
         randomlinks[76]="/Pages/games/spaceinvaders/"
         randomlinks[77]="/Pages/games/steal-this-election/"
         randomlinks[78]="/Pages/games/temple-run-2/"
         randomlinks[79]="/Pages/games/tic-tac-toe/"
         randomlinks[80]="/Pages/games/towermaster/"
         randomlinks[81]="/Pages/games/tyronetetris/"
         randomlinks[82]="/Pages/games/vex6/"
         randomlinks[83]="/Pages/games/whac-a-mole/"
         randomlinks[84]="/Pages/games/wordle/"
         randomlinks[85]="/Pages/games/boxing-physics/index.html"
         randomlinks[86]="/Pages/games/retrohaunt/"









        
        function randomlink(){
        window.location=randomlinks[Math.floor(Math.random()*randomlinks.length)]
        }